version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test -- --watchAll=false --passWithNoTests

  deploy:
    working_directory: ~/repo
    docker:
      - image: katafractari/node-10-python-aws-cli
    steps:
      - checkout
      - run: npm run build
      - run: aws s3 sync build/ s3://${BUCKET_NAME}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
