version: 2.1
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: katafractari/node-10-python-aws-cli
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: aws s3 sync --acl public-read build/ s3://${BUCKET_NAME}

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
